/** @format */

// Check out at 'http://ionicframework.com/docs/v2/ionicons/' for more icons
// '@expo/vector-icons/Ionicons'
const Ionicons = {
  Menu: 'menu',
  Home: 'home',
  HomeOutline: 'home',
  Back: 'arrow-back',
  Forward: 'arrow-forward',
  Config: 'settings',
  More: 'more',
  SignIn: 'log-in',
  SignOut: 'log-out',
  ShoppingCart: 'cart',
  ShoppingCartEmpty: 'cart',
  Sort: 'funnel',
  Filter: 'funnel',
  ShowItem: 'arrow-dropright',
  HideItem: 'arrow-dropup',
  ListMode: 'list-box',
  GridMode: 'grid',
  Star: 'star',
  StarOutline: 'star',
  Wishlist: 'heart',
  WishlistEmpty: 'heart',
  Delete: 'trash',
  AddToCart: 'cart',
  MyOrder: 'cube',
  News: 'paper',
  Mail: 'mail',
  RatioOff: 'radio-button-off',
  RatioOn: 'radio-button-on',
  Search: 'search',
  Close: 'close',
  HappyFace: 'happy',
  SadFace: 'sad',
  ChatBubble: 'chatbubbles',
  ChatBubbleOutline: 'chatbubbles',
  Information: 'information',
  Person: 'person',
  PersonOutline: 'person',
  DropDown: 'arrow-down-outline',
  Facebook: 'logo-facebook',
  Google: 'logo-google',
  Notifications: 'notifications',
  Camera: 'logo-instagram',
  Contact: 'contact',
  Email: 'md-mail',
  Lock: 'md-lock',
  CheckCircle: 'checkmark-circle',
  RemoveCircle: 'remove-circle',
  PriceTags: 'pricetags',
  CheckMark: 'checkmark',
  Categories: 'md-options',
  Down: 'arrow-down',
  Add: 'add',
  Remove: 'remove',
  DownArrow: 'arrow-down-outline',
  RightArrow: 'md-arrow-dropright',
  Phone: 'call',
};

// https://materialdesignicons.com/
// '@expo/vector-icons/MaterialCommunityIcons'
const MaterialCommunityIcons = {
  Menu: 'menu',
  Home: 'home',
  SignIn: 'login',
  Settings: 'settings',
  SignOut: 'logout',
  ShoppingCart: 'cart', // old : cart
  ShoppingCartEmpty: 'cart',
  ShoppingCartAdd: 'cart-plus',
  ListMode: 'view-agenda',
  GridMode: 'view-grid',
  Star: 'star',
  StarOutline: 'star',
  Wishlist: 'heart',
  WishlistEmpty: 'heart',
  Delete: 'delete',
  MyOrder: 'truck-delivery',
  News: 'newspaper',
  Mail: 'mail',
  Search: 'magnify',
  Facebook: 'facebook',
  Google: 'google',
  Email: 'email',
  Lock: 'lock',
  Category: 'format-list-bulleted-type',
  CheckMark: 'check',
  Back: 'arrow-left',
  Forward: 'arrow-right',
  Down: 'arrow-down',
  Contact: 'email',
  Categories: 'format-list-bulleted',
  Pin: 'map-marker',
  Setting: 'settings',
  SMS: 'message-text',
  Phone: 'md-call',
};

export default { MaterialCommunityIcons, Ionicons };
