export default {
  Exit: 'Salir',
  ExitConfirm: '¿Estás seguro de que quieres salir de esta aplicación?',
  YES: 'SÍ',
  OK: 'OK',
  ViewMyOrders: 'Ver Mis Pedidos',
  CANCEL: 'CANCELAR',
  Confirm: 'Confirmar',

  // Scene's Titles
  Home: 'Inicio',
  Intro: 'Introducción',
  Product: 'Producto',
  Cart: 'Carrito',
  WishList: 'Lista de Deseos',

  // Home
  products: 'productos',

  // TopBarz
  ShowFilter: 'Subcategorías',
  HideFilter: 'Ocultar',
  Sort: 'Ordenar',
  textFilter: 'Recientes',

  // Category
  ThereIsNoMore: 'No hay más productos para mostrar',

  // Product
  AddtoCart: 'Agregar al Carrito',
  AddtoWishlist: 'Agregar a la Lista de Deseos',
  ProductVariations: 'Variaciones',
  NoVariation: 'Este producto no tiene variaciones',
  AdditionalInformation: 'Descripción',
  NoProductDescription: 'Sin Descripción del Producto',
  ProductReviews: 'Reseñas',
  NoReview: 'Este producto no tiene reseñas ...aún',
  BUYNOW: 'COMPRAR AHORA',
  OutOfStock: 'AGOTADO',
  ProductLimitWaring: 'No puedes agregar más de {num} productos',
  EmptyProductAttribute: 'Este producto no tiene atributos',
  ProductFeatures: 'Características',
  ErrorMessageRequest: 'No se pueden obtener datos del servidor',
  NoConnection: 'Sin conexión a Internet',
  ProductRelated: 'Productos Relacionados',

  // Cart
  NoCartItem: 'No hay productos en el carrito',
  Total: 'Total',
  EmptyCheckout: 'Lo siento, no puedes finalizar la compra con un carrito vacío',
  RemoveCartItemConfirm: '¿Eliminar este producto del carrito?',
  MyCart: 'Carrito',
  Order: 'Pedido',
  ShoppingCart: 'Carrito de Compras',
  ShoppingCartIsEmpty: 'Tu carrito está vacío',
  AddProductToCart: 'Agregar un producto al carrito de compras',
  TotalPrice: 'Precio Total:',
  YourDeliveryInfo: 'Tu Detalle de Envío',
  ShopNow: 'Comprar Ahora',
  YourChoice: 'Tu carrito:',
  YourSale: 'Tu Descuento:',
  SubtotalPrice: 'Precio Subtotal:',
  BuyNow: 'Comprar Ahora',
  Items: 'artículos',
  Item: 'artículo',
  ThankYou: 'Gracias',
  FinishOrderCOD: 'Puedes usar el número de pedido para rastrear el estado del envío',
  FinishOrder:
    'Muchas gracias por tu compra, para verificar el estado de tu envío, por favor ve a Mis Pedidos',
  NextStep: 'Próximo Paso',
  ConfirmOrder: 'Confirmar Pedido',
  RequireEnterAllFileds: 'Por favor completa todos los campos',
  Error: 'Error',
  InvalidEmail: 'Dirección de correo electrónico inválida',
  Finish: 'Finalizar',

  // Wishlist
  NoWishListItem: 'No hay artículos en la lista de deseos',
  MoveAllToCart: 'Agregar todo al carrito',
  EmptyWishList: 'Lista de deseos vacía',
  EmptyAddToCart: 'Lo siento, la lista de deseos está vacía',
  RemoveWishListItemConfirm: '¿Eliminar este producto de la lista de deseos?',
  CleanAll: 'Limpiar Todo',

  // Sidemenu
  SignIn: 'Iniciar Sesión',
  SignOut: 'Cerrar Sesión',
  GuestAccount: 'Cuenta de Invitado',
  CantReactEmailError:
    'No podemos acceder a tu dirección de correo electrónico, por favor intenta con otro método de inicio de sesión',
  NoEmailError: 'Tu cuenta no tiene una dirección de correo electrónico válida',
  EmailIsNotVerifiedError:
    'Tu dirección de correo electrónico no está verificada, no podemos confiar en ti',
  Login: 'Iniciar Sesión',
  Logout: 'Cerrar Sesión',
  Shop: 'Tienda',
  Category: 'Categoría',

  // Checkout
  Checkout: 'Finalizar Compra',
  ProceedPayment: 'Proceder al Pago',
  Purchase: 'Comprar',
  CashOnDelivery: 'Pago Contra Entrega',
  CreditCard: 'Tarjeta de Crédito',
  PaymentMethod: 'Método de Pago - No seleccionado',
  PaymentMethodError: 'Por favor selecciona tu método de pago',
  PayWithCoD: 'Tu compra será pagada cuando los productos sean entregados',
  PayWithPayPal: 'Tu compra será pagada con PayPal',
  Paypal: 'paypal',
  Stripe: 'stripe',
  PayWithStripe: 'Tu compra será pagada con Stripe',
  ApplyCoupon: 'Aplicar',
  CouponPlaceholder: 'Código de Cupón',
  Apply: 'Aplicar',
  Applying: 'Aplicando',
  Back: 'Atrás',
  CardNamePlaceholder: 'Nombre escrito en la tarjeta',
  BackToHome: 'Volver al Inicio',
  OrderCompleted: 'Tu pedido fue completado',
  OrderCanceled: 'Tu pedido fue cancelado',
  OrderFailed: 'Algo salió mal...',
  OrderCompletedDesc: 'El ID de tu pedido es ',
  OrderCanceledDesc:
    'Has cancelado el pedido. La transacción no se ha completado',
  OrderFailedDesc:
    'Hemos encontrado un error al procesar tu pedido. La transacción no se ha completado. Por favor intenta de nuevo',
  OrderTip:
    'Consejo: Puedes rastrear el estado de tu pedido en la sección "Mis Pedidos" del menú lateral',
  Delivery: 'Dirección',
  Payment: 'Pago',
  Complete: 'Completar',
  EnterYourFirstName: 'Ingresa tu Nombre',
  EnterYourLastName: 'Ingresa tu Apellido',
  EnterYourEmail: 'Ingresa tu correo electrónico',
  EnterYourPhone: 'Ingresa tu teléfono',
  EnterYourAddress: 'Ingresa tu dirección',
  CreateOrderError: 'No se puede crear un nuevo pedido. Por favor intenta más tarde',

  // myorder
  OrderId: 'ID de Pedido',
  MyOrder: 'Mi Pedido',
  NoOrder: 'No tienes ningún pedido',
  OrderDate: 'Fecha de Pedido: ',
  OrderStatus: 'Estado: ',
  OrderPayment: 'Método de pago: ',
  OrderTotal: 'Total: ',
  OrderDetails: 'Mostrar detalle',
  OrderLineItems: 'Artículos del Pedido: ',
  ShippingAddress: 'Dirección de Envío:',
  Refund: 'Reembolso',

  News: 'Noticias',
  PostDetails: 'Detalles del Post',
  FeatureArticles: 'Artículos Destacados',
  MostViews: 'Más Vistos',
  EditorChoice: 'Elección del Editor',

  // settings
  Settings: 'Configuración',
  BASICSETTINGS: 'CONFIGURACIÓN BÁSICA',
  Language: 'Idioma',
  INFO: 'INFORMACIÓN',
  About: 'Sobre nosotros',

  // language
  AvailableLanguages: 'Idiomas Disponibles',
  SwitchLanguage: 'Cambiar Idioma',
  SwitchLanguageConfirm: 'Cambiar el idioma requiere reiniciar la aplicación, ¿continuar?',

  // about us
  AppName: 'MSTORE',
  AppDescription: 'Plantilla React Native para mCommerce',
  AppContact: ' Contáctanos en: mstore.io',
  AppEmail: ' Correo electrónico: support@mstore.io',
  AppCopyRights: '© MSTORE 2016',

  // contact us
  contactus: 'Contáctanos',

  // form
  NotSelected: 'No seleccionado',
  EmptyError: 'Este campo está vacío',
  DeliveryInfo: 'Información de Entrega',
  FirstName: 'Nombre',
  LastName: 'Apellido',
  Address: 'Dirección',
  City: 'Ciudad',
  State: 'Estado',
  NotSelectedError: 'Por favor elige uno',
  Postcode: 'Código Postal',
  Country: 'País',
  Email: 'Correo Electrónico',
  Phone: 'Número de Teléfono',
  Note: 'Nota',

  // search
  Search: 'Buscar',
  SearchPlaceHolder: 'Buscar producto por nombre',
  NoResultError: 'Tu búsqueda no coincidió con ningún producto.',
  Details: 'Detalles',

  // filter panel
  Categories: 'Categorías',
  Loading: 'CARGANDO...',
  welcomeBack: '¡Bienvenido de nuevo!',
  seeAll: 'Mostrar Todo',

  // Layout
  cardView: 'Vista de Tarjeta',
  simpleView: 'Vista de Lista',
  twoColumnView: 'Vista de Dos Columnas',
  threeColumnView: 'Vista de Tres Columnas',
  listView: 'Vista de Lista',
  default: 'Por Defecto',
  advanceView: 'Vista Avanzada',
  horizontal: 'Horizontal',

  couponCodeIsExpired: 'Este código de cupón ha expirado',
  invalidCouponCode: 'Este código de cupón no es válido',
  remove: 'Eliminar',
  applyCouponSuccess: '¡Felicidades! Código de cupón aplicado con éxito',
  reload: 'Recargar',

  ShippingType: 'Método de envío',

  // Place holder
  TypeFirstName: 'Escribe tu nombre',
  TypeLastName: 'Escribe tu apellido',
  TypeAddress: 'Escribe la dirección',
  TypeCity: 'Escribe tu ciudad',
  TypeState: 'Escribe tu estado',
  TypeNotSelectedError: 'Por favor elige uno',
  TypePostcode: 'Escribe el código postal',
  TypeEmail: 'Escribe el correo electrónico (Ej. acb@gmail.com)',
  TypePhone: 'Ej. 123456789',
  TypeNote: 'Nota',
  TypeCountry: 'Selecciona el país',
  SelectPayment: 'Selecciona método de pago',
  close: 'CERRAR',
  noConnection: 'SIN ACCESO A INTERNET',

  // user profile screen
  AccountInformations: 'Información de la Cuenta',
  PushNotification: 'Notificación Push',
  DarkTheme: 'Tema Oscuro',
  Privacy: 'Política de Privacidad',
  SelectCurrency: 'Seleccionar moneda',
  Name: 'Nombre',
  Currency: 'Moneda',
  Languages: 'Idiomas',
  Guest: 'Invitado',
  FacebookLogin: 'Iniciar Sesión con Facebook',
  Or: 'O',
  UserOrEmail: 'Nombre de Usuario o Correo Electrónico',
  DontHaveAccount: '¿No tienes cuenta?',
  accountDetails: 'Detalles de la Cuenta',
  username: 'Nombre de usuario',
  email: 'Correo Electrónico',
  generatePass: 'Usar generar contraseña',
  password: 'Contraseña',
  signup: 'Registrarse',
  profileDetail: 'Detalles del Perfil',
  firstName: 'Nombre',
  lastName: 'Apellido',
  addAddress: 'Añadir dirección',

  // Horizontal
  featureProducts: 'Productos Destacados',
  bagsCollections: 'Colecciones de Bolsos',
  blog: 'Blog',
  womanBestSeller: 'Mujer Más Vendido',
  manCollections: 'Colecciones de Hombres',

  // Modal
  Select: 'Seleccionar',
  Cancel: 'Cancelar',

  // review
  vendorTitle: 'Vendedor',
  comment: 'Deja un comentario',
  yourcomment: 'Tu comentario',
  placeComment:
    'Cuenta algo sobre tu experiencia o deja un consejo para otros',
  writeReview: 'Escribir Reseña',
  thanksForReview:
    'Gracias por la reseña, tu contenido será verificado por el administrador y se publicará más tarde',
  errInputComment: 'Por favor ingresa tu contenido para enviar',
  errRatingComment: 'Por favor califica para enviar',
  send: 'Enviar',
  termCondition: 'Términos y Condiciones',
  Subtotal: 'Subtotal',
  Discount: 'Descuento',
  Shipping: 'Envío',
  Recents: 'Recientes',
  Filters: 'Filtros',
  Pricing: 'Precios',
  Filter: 'Filtrar',
  ClearFilter: 'Limpiar Filtro',
  ProductCatalog: 'Catálogo de Productos',
  ProductTags: 'Etiquetas de Productos',
  AddToAddress: 'Agregar a la Dirección',
  OrderNotes: 'Notas del Pedido',

  CanNotLogin: 'No se puede iniciar sesión, algo salió mal',
  PleaseCompleteForm: '¡Por favor completa el formulario!',
  ServerNotResponse: 'El servidor no responde correctamente',
  CanNotRegister: 'No se puede registrar el usuario, por favor intenta de nuevo.',

  UserProfile: 'Perfil del Usuario',
  LoadMore: 'Cargar Más',
};
